name: DBA Dash Continuous Integration

on: push

jobs:
  build:
    name: Build
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        language: [csharp]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Zip 
        shell: powershell
        run: | 
           Get-ChildItem env:
           "DBADash_$($env:GITHUB_REF -replace "refs/tags/").zip"
           $env:GITHUB_REF | Get-Member

