name: Tag and Create Release

on: push

jobs:
  build:
    name: Build
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        language: [csharp]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
          include-prerelease: true
      - name: Build
        run: dotnet build -c CLI
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      - name: Build DB
        run: msbuild dbadashdb -property:Configuration=CLI

      - name: Get Version
        id: GetVersion 
        shell: powershell
        run: | 
          $path = [System.IO.Path]::Combine((Get-Location),"DBADashBuild\CLI\DBADash.dll")
          $version = [System.Reflection.Assembly]::LoadFrom($path).GetName().Version
          $version.ToString(3)
          Write-Output "::set-output name=BUILD_NUMBER::$($version.ToString(3))"

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{steps.GetVersion.outputs.BUILD_NUMBER}}
          release_name: Release ${{steps.GetVersion.outputs.BUILD_NUMBER}}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: true
          prerelease: false